### ISSUE TITLE
Opt-out of prebuilt binaries

### ISSUE THREAD

**Issue by TooTallNate** [mafintosh/node-gyp-build#5]
Is there a way to force compilation during install-time? With `node-pre-gyp` you can pass `--build-from-source` as a flag to npm.

The problem in my case is that the Linux prebuilt binary is libc based, and thus doesn't work on Alpine Linux which uses MUSL.

**Comment by mafintosh** [comment]
Which module is that for? We don't support a flag atm but I'm open to a PR :) We were talking about adding a simple test method to your prebuild as well so node-gyp-build can test if a prebuild works other than trying to require it

**Comment by TooTallNate** [comment]
The module is `utp-native`

**Comment by vweevers** [comment]
Can be closed, https://github.com/mafintosh/node-gyp-build/pull/13 added support for `--build-from-source`.
